Add section on trust domain
ietf-wg-wimse/draft-ietf-wimse-s2s-protocol pull request #62
Opened 2024-09-20 00:51 UTC by jsalowey

2024-09-20 11:04 UTC, yaronf requested changes

2024-09-20 11:04 UTC, yaronf commented on draft-ietf-wimse-s2s-protocol.md
> +A trust domain maps to a trust anchor for validating X.509 certificates and a mechanism to securely obtain a JWK Set {{!RFC7517}} for validating wimse WIT tokens. This mapping MUST be obtained throug
```suggestion
A trust domain is the authority that issues WIMSE certificates and tokens. Trust domains SHOULD be identified by a fully qualified domain name belonging to the organization defining the trust domain.
A trust domain maps to one or more trust anchors for validating X.509 certificates and a mechanism to securely obtain a JWK Set {{!RFC7517}} for validating WIMSE WIT tokens. This mapping MUST be obtained through a secure mechanism that ensures the authenticity and integrity of the mapping is fresh and not compromised.
```

2024-10-10 17:54 UTC, yaronf commented on draft-ietf-wimse-s2s-protocol.md
> +A trust domain is the authority that issues WIMSE certificates and tokens. Trust domains SHOULD be identified by a fully qualified domain name belonging to the organization defining the trust domain.
@jsalowey Quoting Gemini:

> In the context of computer security, a trust domain is a logical grouping of computers and users that share a common set of security policies and authentication mechanisms. This mutual trust allows users in one domain to access resources in another domain within the same trust relationship, streamlining access while maintaining security control.

2024-10-12 21:52 UTC, jsalowey commented on draft-ietf-wimse-s2s-protocol.md
> +A trust domain is the authority that issues WIMSE certificates and tokens. Trust domains SHOULD be identified by a fully qualified domain name belonging to the organization defining the trust domain.
Thanks, paraphrased to "A trust domain is a logical grouping of systems that share a common set of security controls and policies."

2024-10-12 21:53 UTC, merged